# Generated by Django 5.1.6 on 2025-02-11 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cutomers',
            new_name='Customer',
        ),
    ]
